### ISSUE TITLE
fix: Visual bug on iOS with Impeller (Flutter 3.24)

### ISSUE THREAD

**Issue by dario-digregorio** [renancaraujo/omesh#9]
### Bug Description

Hi Renan, nice package!
I wanted to use it but it seems like since Flutter 3.34 on iOS (iPhone XR 17.5.1) with Impeller.
I think it is since the new Flutter version and I used your code example. They all show the same distortion. I could test it on MacOS but it seems fine there.

### Reproduction Steps

1. Install `mesh: ^0.3.0`
2. Use example and run on iOS with Impeller

### Expected Behavior

No distortion just a colored rectangle like in the docs.

### Screenshots

![8907FB39-2C52-4E43-8CC8-1D6A65DD1ADC](https://github.com/user-attachments/assets/ce72fa2a-8fa7-413c-880a-e6c56c2e0eac)

**Comment by renancaraujo** [comment]
I noticed that too 

Unfortunately, there is nothing we can do in the package to workaround that issue  😢

Hopefully this CP will be included in the next flutter hotfix: 
https://github.com/flutter/flutter/issues/153038

**Comment by dario-digregorio** [comment]
Seems like the PR has been merged in the last hotfix https://github.com/flutter/flutter/blob/master/CHANGELOG.md#3241 🥳
I will test it and close this issue if it is working :)

**Comment by renancaraujo** [comment]
Seems like the new version , instead, bought a whole new set of impeller bugs. 

![](https://github.com/user-attachments/assets/23af2152-30ee-45c9-b896-3c7464858ba4)


😢 I have to confess, this is annoying

**Comment by renancaraujo** [comment]
I created an issue on flutter to track the current problem: https://github.com/flutter/flutter/issues/153964

**Comment by renancaraujo** [comment]
Well, since the instability on impeller seems to be specifically when we use `.drawVertices` with a `FragmentShader`, i figured if we pre-render all gradient patches in a temporary canvas, record it into a `ui.Image` instance and then use a `ImageShader`  instead of a `FragmentShader`, impeller wont panic.


It worked! It also fixes the lines we saw on Flutter 3.22.

See #13

**Comment by renancaraujo** [comment]
This should be fixed on [version 0.4.0](https://github.com/renancaraujo/omesh/releases/tag/flutter-0.4.0)
